name: Build and Test
on: [pull_request, push, workflow_dispatch]

jobs:
  build:
    uses: IABTechLab/uid2-shared-actions/.github/workflows/shared-build-and-test.yaml@kcc-UID2-3858-verify-no-of-tests-run
    secrets: inherit
